baseurl            = ""
title              = "S1ckB0y's Cyber Cave"
languageCode       = "en-us"
theme              = "hello-friend-ng"

enableEmoji        = true
enableGitInfo      = true

PygmentsCodeFences = true
PygmentsStyle      = "native"

copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "02-01-2006"
  dateformNumTime = "02-01-2006"
  
  homeSubtitle = "Security & Research Blog"

  disableReadOtherPosts = false

  description = "Security & Research Blog"
  keywords = "homepage, blog, s1ckb0y, security, hacking, red team"

  images = ["/"]
  contentTypeName = "posts"
  enableThemeToggle = true
  defaultTheme = "dark"

  gitUrl = "https://github.com/s1ckb0y1337/s1ckb0y1337.github.io/commit/"

  [params.logo]
    logoText = "Security Stuff"
    logoHomeLink = "/"

  # Social icons
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/s1ckb0y1337"

  [[params.social]]
    name = "github"
    url  = "https://github.com/s1ckb0y1337"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/in/nikos-katsiopis/"

  [params.footer]
    trademark = false
    rss = true
    copyright = true
    author = false

    topText = []
    bottomText = [
      "<a href=\"http://gohugo.io\">Hugo</a> theme by <a href=\"https://github.com/rhazdon\">rhazdon</a>"
    ]

[permalinks]
  posts = "/posts/:year/:month/:title/"

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
  [[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "posts/"
